const CONFIG = {
    introTitle: 'Này cậu à!',
    introDesc: `Nếu trong quá khứ có sai lầm, có nên sửa chữa sai lầm đó không 😞`,
    btnIntro: '👉Cậu ấn vô đây đi👈',
    title: 'Tớ xin lỗi, xin lỗi cậu rất nhiều 😞',
    desc: 'Tớ thành thật xin lỗi cậu 😞',
    btnYes: 'Bắt buộc phải sửa chữa sai lầm',
    btnNo: 'Nên sửa chữa sai lầm đó',
    question:'Cậu bỏ qua cho tớ nhá 😞',
    btnReply: 'Gửi cho tớ',
    reply: 'Tớ bỏ qua cho cậu',
    mess: 'Cảm ơn cậu rất nhiều ❤',
    messDesc: 'Chúc cậu ngủ ngon ❤.',
    btnAccept: 'Okiiiii lun <3',
}
